// Plain-language definitions for the terms that appear in chart legends.
// Legend items render a "?" tooltip pulling its text from here.
export const GLOSSARY: Record<string, string> = {
  OLS: "Ordinary Least Squares — the plain linear fit that minimizes the sum of squared vertical errors. Sensitive to outliers.",
  Huber: "Huber regression — squared loss for small errors but linear loss for large ones, so extreme points pull it far less than OLS.",
  RANSAC: "RANSAC — repeatedly fits on random subsets and keeps the fit the most 'inlier' points agree with, effectively ignoring outliers.",
  "Theil-Sen": "Theil–Sen — takes the median of the slopes between all pairs of points, making it very robust to outliers.",
  Ridge: "Ridge (L2) — shrinks all coefficients smoothly toward zero to curb overfitting, but keeps every feature.",
  Lasso: "Lasso (L1) — shrinks coefficients and drives some to exactly zero, performing automatic feature selection.",
  ElasticNet: "ElasticNet — a blend of the Ridge (L2) and Lasso (L1) penalties.",
  KNN: "k-Nearest Neighbors — predicts from the k closest points: a majority vote for classification, an average for regression.",
  SVR: "Support Vector Regression — fits a tube of width ε around the data and only penalizes points outside it.",
  SVM: "Support Vector Machine — finds the widest margin separating the classes, which a kernel can bend into a curve.",
  LDA: "Linear Discriminant Analysis — a Gaussian classifier that assumes all classes share one covariance, giving straight boundaries.",
  QDA: "Quadratic Discriminant Analysis — like LDA but each class gets its own covariance, giving curved boundaries.",
  "Naive Bayes": "Gaussian Naive Bayes — applies Bayes' theorem assuming each feature is independent within a class.",
  Perceptron: "Perceptron — the original online linear classifier; it nudges its boundary after every misclassified point.",
  "Ridge Classifier": "Ridge Classifier — classifies by solving one regularized least-squares problem, with no iteration.",
  Poisson: "Poisson regression — a generalized linear model for non-negative, count-like targets.",
  Gamma: "Gamma regression — a generalized linear model for strictly positive, right-skewed targets.",
  Tweedie: "Tweedie regression — a GLM whose 'power' parameter interpolates between Normal, Poisson, and Gamma.",
  Bayesian: "Bayesian regression — returns a distribution over fits, yielding a mean line plus an uncertainty band.",
  "Gradient Boosting": "Gradient Boosting — builds many small trees in sequence, each correcting the previous ones' errors.",
  XGBoost: "XGBoost — a fast, regularized implementation of gradient boosting.",
  "Train error": "Training error — the model's error on the data it was fit on; keeps dropping as the model grows more complex.",
  "Test error": "Test error — error on held-out data the model never saw; the honest measure of generalization.",
  Outliers: "Outliers — points far from the real trend (injected here to stress-test each regressor).",
  ROC: "ROC curve — true-positive rate vs. false-positive rate as the threshold varies; up-and-left is better.",
  "Precision–Recall": "Precision–Recall curve — precision vs. recall as the threshold varies; useful when classes are imbalanced.",
};
